services:
  - type: web
    name: ace-card-games
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ace-db
          property: connectionString

databases:
  - name: ace-db
    plan: free
